# Generated by Django 2.2.5 on 2019-10-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.TextField(verbose_name='질문1')),
                ('question2', models.TextField(verbose_name='질문2')),
                ('question3', models.TextField(verbose_name='질문3')),
                ('question4', models.TextField(verbose_name='질문4')),
                ('question5', models.TextField(verbose_name='질문5')),
                ('question6', models.TextField(verbose_name='질문6')),
                ('question7', models.TextField(verbose_name='질문7')),
                ('question8', models.TextField(verbose_name='질문8')),
                ('question9', models.TextField(verbose_name='질문9')),
                ('question10', models.TextField(verbose_name='질문10')),
                ('question11', models.TextField(verbose_name='질문11')),
                ('question12', models.TextField(verbose_name='질문12')),
                ('question13', models.TextField(verbose_name='질문13')),
                ('question14', models.TextField(verbose_name='질문14')),
                ('question15', models.TextField(verbose_name='질문15')),
                ('question16', models.TextField(verbose_name='질문16')),
            ],
        ),
    ]
