# Generated by Django 2.2.5 on 2019-10-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.TextField(verbose_name='답변1')),
                ('answer2', models.TextField(verbose_name='답변2')),
                ('answer3', models.TextField(verbose_name='답변3')),
                ('answer4', models.TextField(verbose_name='답변4')),
                ('answer5', models.TextField(verbose_name='답변5')),
                ('answer6', models.TextField(verbose_name='답변6')),
                ('answer7', models.TextField(verbose_name='답변7')),
                ('answer8', models.TextField(verbose_name='답변8')),
                ('answer9', models.TextField(verbose_name='답변9')),
                ('answer10', models.TextField(verbose_name='답변10')),
                ('answer11', models.TextField(verbose_name='답변11')),
                ('answer12', models.TextField(verbose_name='답변12')),
                ('answer13', models.TextField(verbose_name='답변13')),
                ('answer14', models.TextField(verbose_name='답변14')),
                ('answer15', models.TextField(verbose_name='답변15')),
                ('answer16', models.TextField(verbose_name='답변16')),
            ],
        ),
    ]
