# Generated by Django 2.2.6 on 2019-11-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20191024_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlist',
            name='author',
            field=models.CharField(default='', max_length=16, verbose_name='작성자'),
        ),
    ]
