# Generated by Django 2.2.6 on 2019-11-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20191110_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlist',
            name='my_resume',
            field=models.IntegerField(default=0),
        ),
    ]
