# Generated by Django 2.2.6 on 2019-11-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20191110_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionlist',
            name='my_resume',
        ),
    ]
