# Generated by Django 2.2.6 on 2019-11-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_remove_questionlist_my_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlist',
            name='my_resume',
            field=models.IntegerField(default=0),
        ),
    ]
