# Generated by Django 2.2.6 on 2019-11-10 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_questionlist_my_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionlist',
            name='my_resume',
        ),
    ]
