# Generated by Django 2.2.5 on 2019-11-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_questionlist_my_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlist',
            name='answer17',
            field=models.TextField(default='', verbose_name='답변17'),
        ),
        migrations.AddField(
            model_name='questionlist',
            name='answer18',
            field=models.TextField(default='', verbose_name='답변18'),
        ),
        migrations.AddField(
            model_name='questionlist',
            name='answer19',
            field=models.TextField(default='', verbose_name='답변19'),
        ),
        migrations.AddField(
            model_name='questionlist',
            name='answer20',
            field=models.TextField(default='', verbose_name='답변20'),
        ),
        migrations.AddField(
            model_name='questionlist',
            name='question17',
            field=models.TextField(default='', verbose_name='질문17'),
        ),
        migrations.AddField(
            model_name='questionlist',
            name='question18',
            field=models.TextField(default='', verbose_name='질문18'),
        ),
        migrations.AddField(
            model_name='questionlist',
            name='question19',
            field=models.TextField(default='', verbose_name='질문19'),
        ),
        migrations.AddField(
            model_name='questionlist',
            name='question20',
            field=models.TextField(default='', verbose_name='질문20'),
        ),
    ]
