# Generated by Django 2.2.6 on 2019-11-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_auto_20191112_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlist',
            name='answer_alltext',
            field=models.TextField(default='', verbose_name='전체답변'),
        ),
        migrations.AddField(
            model_name='questionlist',
            name='answer_mbti',
            field=models.TextField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='questionlist',
            name='answer_mbti_E',
            field=models.FloatField(default=0, verbose_name='E'),
        ),
        migrations.AddField(
            model_name='questionlist',
            name='answer_mbti_F',
            field=models.FloatField(default=0, verbose_name='F'),
        ),
        migrations.AddField(
            model_name='questionlist',
            name='answer_mbti_I',
            field=models.FloatField(default=0, verbose_name='I'),
        ),
        migrations.AddField(
            model_name='questionlist',
            name='answer_mbti_J',
            field=models.FloatField(default=0, verbose_name='J'),
        ),
        migrations.AddField(
            model_name='questionlist',
            name='answer_mbti_N',
            field=models.FloatField(default=0, verbose_name='N'),
        ),
        migrations.AddField(
            model_name='questionlist',
            name='answer_mbti_P',
            field=models.FloatField(default=0, verbose_name='P'),
        ),
        migrations.AddField(
            model_name='questionlist',
            name='answer_mbti_S',
            field=models.FloatField(default=0, verbose_name='S'),
        ),
        migrations.AddField(
            model_name='questionlist',
            name='answer_mbti_T',
            field=models.FloatField(default=0, verbose_name='T'),
        ),
    ]
