# Generated by Django 2.2.5 on 2019-11-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_auto_20191128_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionlist',
            old_name='answer_mbti',
            new_name='mbti',
        ),
        migrations.RemoveField(
            model_name='questionlist',
            name='answer_alltext',
        ),
        migrations.AddField(
            model_name='questionlist',
            name='mbti1',
            field=models.TextField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='questionlist',
            name='mbti2',
            field=models.TextField(default='', max_length=32),
        ),
    ]
