# Generated by Django 2.2.5 on 2019-11-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_questionlist_answer_alltext'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlist',
            name='word',
            field=models.TextField(default='', verbose_name='단어'),
        ),
        migrations.AddField(
            model_name='questionlist',
            name='word_count',
            field=models.TextField(default='', verbose_name='단어 갯수'),
        ),
    ]
