# Generated by Django 2.2.5 on 2019-11-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_auto_20191129_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlist',
            name='famous',
            field=models.TextField(default='', max_length=32),
        ),
    ]
