# Generated by Django 2.2.5 on 2019-12-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_questionlist_famous'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestQuestionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=16, verbose_name='작성자')),
                ('my_resume', models.IntegerField(default=0)),
                ('question1', models.TextField(default='', verbose_name='질문1')),
                ('question2', models.TextField(default='', verbose_name='질문2')),
                ('question3', models.TextField(default='', verbose_name='질문3')),
                ('question4', models.TextField(default='', verbose_name='질문4')),
                ('question5', models.TextField(default='', verbose_name='질문5')),
                ('question6', models.TextField(default='', verbose_name='질문6')),
                ('answer1', models.TextField(default='', verbose_name='답변1')),
                ('answer2', models.TextField(default='', verbose_name='답변2')),
                ('answer3', models.TextField(default='', verbose_name='답변3')),
                ('answer4', models.TextField(default='', verbose_name='답변4')),
                ('answer5', models.TextField(default='', verbose_name='답변5')),
                ('answer6', models.TextField(default='', verbose_name='답변6')),
            ],
        ),
    ]
