# Generated by Django 2.2.1 on 2019-09-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_activity_growth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('question', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='Other',
        ),
    ]
