# Generated by Django 2.2.5 on 2019-10-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_my_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='my_resume',
            field=models.CharField(choices=[('', ''), ('삼성전자 상반기 이력서', '삼성전자 상반기 이력서')], default=True, max_length=80),
        ),
    ]
