# Generated by Django 2.2.6 on 2019-11-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191028_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='my_resume',
            field=models.CharField(choices=[('', ''), ('02.실전! 합격자소서', '02.실전! 합격자소서')], default=True, max_length=80),
        ),
    ]
