# Generated by Django 2.2.6 on 2019-11-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191109_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='my_resume',
            field=models.IntegerField(default=0),
        ),
    ]
