# Generated by Django 2.2.6 on 2019-11-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191110_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='my_resume',
            field=models.IntegerField(blank=True),
        ),
    ]
