# Generated by Django 2.2.1 on 2019-11-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20191110_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='my_mbti',
            field=models.CharField(blank=True, max_length=30, verbose_name='MBTI'),
        ),
    ]
