# Generated by Django 2.2.5 on 2019-11-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1024)),
                ('mbti1', models.TextField(max_length=1024)),
                ('mbti2', models.TextField(max_length=1024)),
            ],
        ),
    ]
