# Generated by Django 2.2.5 on 2019-11-13 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Text',
        ),
    ]
