# Generated by Django 2.2.5 on 2019-10-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_propensity'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='score1',
            field=models.FloatField(default=0, verbose_name='적극적'),
        ),
        migrations.AddField(
            model_name='resume',
            name='score2',
            field=models.FloatField(default=0, verbose_name='열정적'),
        ),
        migrations.AddField(
            model_name='resume',
            name='score3',
            field=models.FloatField(default=0, verbose_name='성실성'),
        ),
        migrations.AddField(
            model_name='resume',
            name='score4',
            field=models.FloatField(default=0, verbose_name='책임감'),
        ),
        migrations.AddField(
            model_name='resume',
            name='score5',
            field=models.FloatField(default=0, verbose_name='사교적'),
        ),
        migrations.AddField(
            model_name='resume',
            name='score6',
            field=models.FloatField(default=0, verbose_name='신중함'),
        ),
    ]
