# Generated by Django 2.2.6 on 2019-11-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20191028_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='MBTI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=16, verbose_name='작성자')),
                ('E', models.FloatField(default=0, verbose_name='E')),
                ('I', models.FloatField(default=0, verbose_name='I')),
                ('N', models.FloatField(default=0, verbose_name='N')),
                ('S', models.FloatField(default=0, verbose_name='S')),
                ('T', models.FloatField(default=0, verbose_name='T')),
                ('F', models.FloatField(default=0, verbose_name='F')),
                ('J', models.FloatField(default=0, verbose_name='J')),
                ('P', models.FloatField(default=0, verbose_name='P')),
            ],
        ),
    ]
