# Generated by Django 2.2.6 on 2019-11-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_mbti_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='result',
            field=models.CharField(default='', max_length=10),
        ),
    ]
