# Generated by Django 2.2.6 on 2019-11-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_auto_20191109_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbti',
            name='my_resume',
            field=models.IntegerField(default=0),
        ),
    ]
