# Generated by Django 2.2.5 on 2019-11-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_mbti_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbti',
            name='mbti1',
            field=models.TextField(default=0, max_length=1024),
        ),
        migrations.AddField(
            model_name='mbti',
            name='mbti2',
            field=models.TextField(default=0, max_length=1024),
        ),
        migrations.AddField(
            model_name='mbti',
            name='text',
            field=models.TextField(default=0, max_length=1024),
        ),
    ]
