# Generated by Django 2.2.5 on 2019-11-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_auto_20191113_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mbti',
            name='mbti1',
        ),
        migrations.RemoveField(
            model_name='mbti',
            name='mbti2',
        ),
        migrations.AddField(
            model_name='mbti',
            name='textEI',
            field=models.TextField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='mbti',
            name='textJP',
            field=models.TextField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='mbti',
            name='textSN',
            field=models.TextField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='mbti',
            name='textTF',
            field=models.TextField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='mbti',
            name='textfinal',
            field=models.TextField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='text',
            field=models.TextField(default='', max_length=1024),
        ),
    ]
