# Generated by Django 2.2.5 on 2019-11-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_auto_20191114_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbti',
            name='mbti1',
            field=models.TextField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='mbti',
            name='mbti2',
            field=models.TextField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='text',
            field=models.TextField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='textfinal',
            field=models.TextField(default='', max_length=64),
        ),
    ]
