# Generated by Django 2.2.5 on 2019-11-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_auto_20191114_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbti',
            name='Ambti1',
            field=models.TextField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='mbti',
            name='Ambti2',
            field=models.TextField(default='', max_length=1024),
        ),
    ]
