# Generated by Django 2.2.5 on 2019-11-15 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0017_auto_20191114_1622'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MBTI_score',
        ),
    ]
