# Generated by Django 2.2.5 on 2019-12-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0018_delete_mbti_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='All',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all', models.TextField(default='', verbose_name='전체자소서')),
                ('word', models.TextField(default='', verbose_name='단어')),
                ('word_count', models.TextField(default='', verbose_name='단어 갯수')),
            ],
        ),
    ]
