# Generated by Django 2.2.5 on 2019-09-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190915_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=126, verbose_name='제목'),
        ),
    ]
