# Generated by Django 2.2.5 on 2019-09-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190917_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='docfile',
            field=models.FileField(null=True, upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성일'),
        ),
    ]
