# Generated by Django 2.2.5 on 2019-11-13 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20190924_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='docfile',
        ),
    ]
